# Form implementation generated from reading ui file 'ui_design/rand_movie_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RandMovieWindow(object):
    def setupUi(self, RandMovieWindow):
        RandMovieWindow.setObjectName("RandMovieWindow")
        RandMovieWindow.resize(682, 740)
        RandMovieWindow.setStyleSheet("/* Основной фон окна */\n"
"QMainWindow {\n"
"    background-color: #121423;\n"
"}\n"
"\n"
"/* СТИЛЬ КНОПКИ (у вас уже есть, оставляем) */\n"
"QPushButton {\n"
"    background-color: #8e3d0a; \n"
"    color: white; \n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a85216;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6b2e08;\n"
"    margin-top: 4px;\n"
"    margin-left: 4px;\n"
"}\n"
"\n"
"/* СТИЛЬ МЕНЮ БАРА (верхняя панель) */\n"
"QMenuBar {\n"
"    background-color: #1a1c2e;\n"
"    color: #ffffff;\n"
"    font-family: \'Corbel\';\n"
"    font-size: 18px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 8px 15px;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: rgba(142, 61, 10, 0.7); /* Полупрозрачный оранжевый */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background-color: #8e3d0a; /* Тот же цвет что и кнопка */\n"
"}\n"
"\n"
"/* СТИЛЬ ВЫПАДАЮЩЕГО МЕНЮ */\n"
"QMenu {\n"
"    background-color: #1a1c2e;\n"
"    border: 1px solid #2a2c3e;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent;\n"
"    padding: 10px 20px;\n"
"    margin: 2px;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: rgba(142, 61, 10, 0.7); /* Полупрозрачный оранжевый */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"    background-color: #8e3d0a; /* Тот же цвет что и кнопка */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #2a2c3e;\n"
"    margin: 5px 10px;\n"
"}\n"
"\n"
"/* СТИЛЬ ЭЛЕМЕНТОВ МЕНЮ (действий) */\n"
"QAction {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* СТИЛЬ МЕТКИ ДЛЯ ИЗОБРАЖЕНИЯ */\n"
"QLabel {\n"
"    background-color: #494c5c; \n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px;\n"
"    font-family: Arial;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=RandMovieWindow)
        self.centralwidget.setStyleSheet("background-color: #121423;")
        self.centralwidget.setObjectName("centralwidget")
        self.rand_movie_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rand_movie_button.setGeometry(QtCore.QRect(130, 610, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rand_movie_button.setFont(font)
        self.rand_movie_button.setStyleSheet("QPushButton {\n"
"    background-color: #8e3d0a; \n"
"    color: white; \n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a85216;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6b2e08;\n"
"    margin-top: 4px;\n"
"    margin-left: 4px;\n"
"}")
        self.rand_movie_button.setAutoRepeatInterval(100)
        self.rand_movie_button.setObjectName("rand_movie_button")
        self.label_poster = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_poster.setGeometry(QtCore.QRect(200, 10, 300, 300))
        self.label_poster.setMinimumSize(QtCore.QSize(300, 300))
        self.label_poster.setMaximumSize(QtCore.QSize(300, 300))
        self.label_poster.setStyleSheet("background-color: #494c5c; \n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px;\n"
"    font-family: Arial;")
        self.label_poster.setText("")
        self.label_poster.setScaledContents(True)
        self.label_poster.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_poster.setWordWrap(True)
        self.label_poster.setObjectName("label_poster")
        self.label_film_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_film_title.setGeometry(QtCore.QRect(130, 330, 81, 60))
        self.label_film_title.setStyleSheet("color: #a85216; font-size: 16px;")
        self.label_film_title.setObjectName("label_film_title")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(240, 330, 300, 60))
        self.label_name.setStyleSheet("color: white; font-size: 16px;")
        self.label_name.setObjectName("label_name")
        self.label_year_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_year_title.setGeometry(QtCore.QRect(130, 390, 51, 60))
        self.label_year_title.setStyleSheet("color: #a85216; font-size: 16px;")
        self.label_year_title.setObjectName("label_year_title")
        self.label_year = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_year.setGeometry(QtCore.QRect(240, 390, 300, 60))
        self.label_year.setStyleSheet("color: white; font-size: 16px; ")
        self.label_year.setObjectName("label_year")
        self.label_desc_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_desc_title.setGeometry(QtCore.QRect(130, 460, 101, 60))
        self.label_desc_title.setStyleSheet("color: #a85216; font-size: 16px;")
        self.label_desc_title.setObjectName("label_desc_title")
        self.label_description = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_description.setGeometry(QtCore.QRect(240, 450, 300, 130))
        self.label_description.setStyleSheet("color: white; font-size: 16px;")
        self.label_description.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.label_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        RandMovieWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RandMovieWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 49))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(-1)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: #8b8d90;")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        RandMovieWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RandMovieWindow)
        self.statusbar.setObjectName("statusbar")
        RandMovieWindow.setStatusBar(self.statusbar)
        self.action_random_cat = QtGui.QAction(parent=RandMovieWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_cat.setFont(font)
        self.action_random_cat.setObjectName("action_random_cat")
        self.action_random_dog = QtGui.QAction(parent=RandMovieWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_dog.setFont(font)
        self.action_random_dog.setObjectName("action_random_dog")
        self.action_random_film = QtGui.QAction(parent=RandMovieWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_film.setFont(font)
        self.action_random_film.setObjectName("action_random_film")
        self.action_film_by_name = QtGui.QAction(parent=RandMovieWindow)
        self.action_film_by_name.setObjectName("action_film_by_name")
        self.menu.addAction(self.action_random_cat)
        self.menu.addAction(self.action_random_dog)
        self.menu.addAction(self.action_random_film)
        self.menu.addAction(self.action_film_by_name)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(RandMovieWindow)
        QtCore.QMetaObject.connectSlotsByName(RandMovieWindow)

    def retranslateUi(self, RandMovieWindow):
        _translate = QtCore.QCoreApplication.translate
        RandMovieWindow.setWindowTitle(_translate("RandMovieWindow", "Api - app"))
        self.rand_movie_button.setText(_translate("RandMovieWindow", "Рандомный фильм"))
        self.label_film_title.setText(_translate("RandMovieWindow", "Фильм:"))
        self.label_name.setText(_translate("RandMovieWindow", "тут будет имя фильма"))
        self.label_year_title.setText(_translate("RandMovieWindow", "Год: "))
        self.label_year.setText(_translate("RandMovieWindow", "тут будет год"))
        self.label_desc_title.setText(_translate("RandMovieWindow", "Описание:"))
        self.label_description.setText(_translate("RandMovieWindow", "тут будет описание фильма"))
        self.menu.setTitle(_translate("RandMovieWindow", "Меню"))
        self.action_random_cat.setText(_translate("RandMovieWindow", "Рандомный кот"))
        self.action_random_dog.setText(_translate("RandMovieWindow", "Рандомная собака"))
        self.action_random_film.setText(_translate("RandMovieWindow", "Рандомный фильм"))
        self.action_film_by_name.setText(_translate("RandMovieWindow", "Поиск фильма"))
