# Form implementation generated from reading ui file 'ui_design/simple_dog_app.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RandDogWindow(object):
    def setupUi(self, RandDogWindow):
        print("ПРедустановка")
        RandDogWindow.setObjectName("RandDogWindow")
        RandDogWindow.resize(500, 600)
        RandDogWindow.setStyleSheet("/* Основной фон окна */\n"
"QMainWindow {\n"
"    background-color: #121423;\n"
"}\n"
"\n"
"/* СТИЛЬ КНОПКИ (у вас уже есть, оставляем) */\n"
"QPushButton {\n"
"    background-color: #8e3d0a; \n"
"    color: white; \n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a85216;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6b2e08;\n"
"    margin-top: 4px;\n"
"    margin-left: 4px;\n"
"}\n"
"\n"
"/* СТИЛЬ МЕНЮ БАРА (верхняя панель) */\n"
"QMenuBar {\n"
"    background-color: #1a1c2e;\n"
"    color: #ffffff;\n"
"    font-family: \'Corbel\';\n"
"    font-size: 18px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 8px 15px;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: rgba(142, 61, 10, 0.7); /* Полупрозрачный оранжевый */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background-color: #8e3d0a; /* Тот же цвет что и кнопка */\n"
"}\n"
"\n"
"/* СТИЛЬ ВЫПАДАЮЩЕГО МЕНЮ */\n"
"QMenu {\n"
"    background-color: #1a1c2e;\n"
"    border: 1px solid #2a2c3e;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent;\n"
"    padding: 10px 20px;\n"
"    margin: 2px;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: rgba(142, 61, 10, 0.7); /* Полупрозрачный оранжевый */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"    background-color: #8e3d0a; /* Тот же цвет что и кнопка */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #2a2c3e;\n"
"    margin: 5px 10px;\n"
"}\n"
"\n"
"/* СТИЛЬ ЭЛЕМЕНТОВ МЕНЮ (действий) */\n"
"QAction {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* СТИЛЬ МЕТКИ ДЛЯ ИЗОБРАЖЕНИЯ */\n"
"QLabel {\n"
"    background-color: #494c5c; \n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px;\n"
"    font-family: Arial;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=RandDogWindow)
        self.centralwidget.setStyleSheet("background-color: #121423;")
        self.centralwidget.setObjectName("centralwidget")
        self.rand_dog_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rand_dog_button.setGeometry(QtCore.QRect(80, 430, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rand_dog_button.setFont(font)
        self.rand_dog_button.setStyleSheet("QPushButton {\n"
"    background-color: #8e3d0a; \n"
"    color: white; \n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a85216;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6b2e08;\n"
"    margin-top: 4px;\n"
"    margin-left: 4px;\n"
"}")
        self.rand_dog_button.setAutoRepeatInterval(100)
        self.rand_dog_button.setObjectName("rand_dog_button")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 90, 300, 300))
        self.label.setMinimumSize(QtCore.QSize(300, 300))
        self.label.setMaximumSize(QtCore.QSize(300, 300))
        self.label.setStyleSheet("background-color: #494c5c; \n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 10px;\n"
"    font-family: Arial;")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        RandDogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RandDogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 49))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(-1)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: #8b8d90;")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        RandDogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RandDogWindow)
        self.statusbar.setObjectName("statusbar")
        RandDogWindow.setStatusBar(self.statusbar)
        self.action_random_cat = QtGui.QAction(parent=RandDogWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_cat.setFont(font)
        self.action_random_cat.setObjectName("action_random_cat")
        self.action_random_dog = QtGui.QAction(parent=RandDogWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_dog.setFont(font)
        self.action_random_dog.setObjectName("action_random_dog")
        self.action_random_film = QtGui.QAction(parent=RandDogWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.action_random_film.setFont(font)
        self.action_random_film.setObjectName("action_random_film")
        self.action_film_by_name = QtGui.QAction(parent=RandDogWindow)
        self.action_film_by_name.setObjectName("action_film_by_name")
        self.menu.addAction(self.action_random_cat)
        self.menu.addAction(self.action_random_dog)
        self.menu.addAction(self.action_random_film)
        self.menu.addAction(self.action_film_by_name)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(RandDogWindow)
        QtCore.QMetaObject.connectSlotsByName(RandDogWindow)

    def retranslateUi(self, RandDogWindow):
        _translate = QtCore.QCoreApplication.translate
        RandDogWindow.setWindowTitle(_translate("RandDogWindow", "Api - app"))
        self.rand_dog_button.setText(_translate("RandDogWindow", "Рандомная собака"))
        self.menu.setTitle(_translate("RandDogWindow", "Меню"))
        self.action_random_cat.setText(_translate("RandDogWindow", "Рандомный кот"))
        self.action_random_dog.setText(_translate("RandDogWindow", "Рандомная собака"))
        self.action_random_film.setText(_translate("RandDogWindow", "Рандомный фильм"))
        self.action_film_by_name.setText(_translate("RandDogWindow", "Поиск фильма"))
